In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import os

In [6]:
def data_corrector(symbol):
    path = '../updatedtop20datasets/'
    filepath = f'{path}{symbol}.parquet'
    if not os.path.exists(filepath):
        print(f"There is no such file for the symbol {symbol}")
        return None
    data = pd.read_parquet(filepath)
    data = data.loc[:, ~data.columns.str.contains('Unnamed')]
    data['date'] = pd.to_datetime(data['date'])
    if data.isna().sum().sum() > 0:
        print(f"Missing Values Detected for symbol {symbol}, Fixed using forward fill")
        data = data.ffill()
    if data.duplicated().sum() > 0:
        data = data.drop_duplicates()
        print(f"There are duplicate values for stock {symbol}. Fixed using duplication drop")
    data.to_parquet(filepath, index = False)
    return data

In [7]:
### Creating datasets for the top 20 companies 
watchlist = {
    "AAPL":  "Apple",
    "MSFT":  "Microsoft", 
    "NVDA":  "Nvidia",
    "GOOGL": "Alphabet (Google)",
    "AMD":  "AMD",
    "META":  "Meta (Facebook)",
    "TSLA":  "Tesla",
    "NFLX": "Netflix",
    "LLY":   "Eli Lilly",
    "AVGO":   "Broadcom",
    "MU":    "Micron Technology",
    "QCOM":   "Qualcomm",
    "UNH":   "UnitedHealth",
    "WMT":   "Walmart",
    "MA":    "Mastercard",
    "JNJ":   "Johnson & Johnson",
    "PG":    "Procter & Gamble",
    "HD":    "Home Depot",
    "ORCL":  "Oracle",
    "JPM": "JPMorgan Chase"
}

In [8]:
### Data preprocessing for all the files 
for key,value in watchlist.items():
    data_corrector(key)

### Problem statements: Like I create a parquet file in one notebook and try to update it in the other notebook why does not it update

In [12]:
data = data_corrector("AAPL")
data.head(5)

,date,close,high,low,open,volume,adjClose,adjHigh,adjLow,adjOpen,adjVolume,divCash,splitFactor,Symbol
0,2008-01-02 00:00:00+00:00,194.84,200.26,192.55,199.27,38542100,5.832436,5.994681,5.763886,5.965046,1079179879,0.0,1.0,AAPL
1,2008-01-03 00:00:00+00:00,194.93,197.39,192.69,195.41,30073800,5.835131,5.908769,5.768077,5.849499,842067242,0.0,1.0,AAPL
2,2008-01-04 00:00:00+00:00,180.05,193.00,178.89,191.45,51994000,5.389705,5.777357,5.354981,5.730959,1455833455,0.0,1.0,AAPL
3,2008-01-07 00:00:00+00:00,177.64,183.60,170.23,181.25,74006900,5.317563,5.495973,5.095749,5.425627,2072195272,0.0,1.0,AAPL
4,2008-01-08 00:00:00+00:00,171.25,182.46,170.80,180.14,54422000,5.126282,5.461847,5.112811,5.392399,1523817523,0.0,1.0,AAPL

---
### Creating the new features out of the given columns

In [16]:
def new_features(symbol):
    path = '../updatedtop20datasets/'
    file_path = f'{path}{symbol}.parquet'
    data = pd.read_parquet(file_path)
    data['price_return'] = data['close'].diff() / data['close'].shift(1)
    data['price_return'] = data['price_return'].fillna(0)
    return data

In [17]:
data = new_features("AAPL")
data.head(5)

,date,close,high,low,open,volume,adjClose,adjHigh,adjLow,adjOpen,adjVolume,divCash,splitFactor,Symbol,price_return
0,2008-01-02 00:00:00+00:00,194.84,200.26,192.55,199.27,38542100,5.832436,5.994681,5.763886,5.965046,1079179879,0.0,1.0,AAPL,0.000000
1,2008-01-03 00:00:00+00:00,194.93,197.39,192.69,195.41,30073800,5.835131,5.908769,5.768077,5.849499,842067242,0.0,1.0,AAPL,0.000462
2,2008-01-04 00:00:00+00:00,180.05,193.00,178.89,191.45,51994000,5.389705,5.777357,5.354981,5.730959,1455833455,0.0,1.0,AAPL,-0.076335
3,2008-01-07 00:00:00+00:00,177.64,183.60,170.23,181.25,74006900,5.317563,5.495973,5.095749,5.425627,2072195272,0.0,1.0,AAPL,-0.013385
4,2008-01-08 00:00:00+00:00,171.25,182.46,170.80,180.14,54422000,5.126282,5.461847,5.112811,5.392399,1523817523,0.0,1.0,AAPL,-0.035972