In [180]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import IsolationForest

### We will be using isolation forest to detect the anamolies

In [181]:
data = pd.read_parquet('../updatedtop20datasets/META.parquet')
data.head(5)

                       date    close  ...  volatility_score  cum_score
0 2012-05-18 00:00:00+00:00  38.2318  ...          0.133157   0.070190
1 2012-05-21 00:00:00+00:00  34.0300  ...          0.133157   0.055015
2 2012-05-22 00:00:00+00:00  31.0000  ...          0.133157   0.064989
3 2012-05-23 00:00:00+00:00  32.0000  ...          0.133157   0.139023
4 2012-05-24 00:00:00+00:00  33.0300  ...          0.133157   0.131261

[5 rows x 29 columns]

In [189]:
def data_partition(symbol):
    path = '../updatedtop20datasets/'
    filepath = f'{path}{symbol}.parquet'
    columns =  ['price_return', 'volatility_diff', 'Volatility_30Days', 'Price_Swing', 'volume_z_diff', 'volume_zscore30Days']
    data = pd.read_parquet(filepath)
    scaler = StandardScaler()
    data[columns] = scaler.fit_transform(data[columns])
    data.to_parquet(filepath, index = False)
    return data

In [183]:
def iso_runner(symbol,contamination = 0.05):
    path = '../updatedtop20datasets/'
    filepath = f'{path}{symbol}.parquet'
    data = pd.read_parquet(filepath)
    price_features = ['price_return', 'Price_Swing', 'MASignal']
    volume_features = ['volume_z_diff', 'volume_zscore30Days']
    volatility_features = ['volatility_diff', 'Volatility_30Days']
    
    for features, col_name in zip(
        [price_features, volume_features, volatility_features],
        ['price_score', 'volume_score', 'volatility_score']
    ):
        model = IsolationForest(contamination=contamination, random_state=42)
        model.fit(data[features])
        data[col_name] = model.decision_function(data[features])
    
    data['cum_score'] = (data['price_score'] + 
                         data['volume_score'] + 
                         data['volatility_score']) / 3
    data['is_anomaly'] = (data['cum_score'] < data['cum_score'].quantile(0.05)).astype(int)
    data.to_parquet(filepath, index=False)
    return data

print(data['is_anomaly'].value_counts())

is_anomaly
0    3350
1     177
Name: count, dtype: int64

In [184]:
data.head(5)

                       date    close  ...  volatility_score  cum_score
0 2012-05-18 00:00:00+00:00  38.2318  ...          0.133157   0.070190
1 2012-05-21 00:00:00+00:00  34.0300  ...          0.133157   0.055015
2 2012-05-22 00:00:00+00:00  31.0000  ...          0.133157   0.064989
3 2012-05-23 00:00:00+00:00  32.0000  ...          0.133157   0.139023
4 2012-05-24 00:00:00+00:00  33.0300  ...          0.133157   0.131261

[5 rows x 29 columns]

In [185]:
anomaly = data[data['is_anomaly'] == 1]
anomaly.describe()

            close        high  ...  volatility_score   cum_score
count  177.000000  177.000000  ...        177.000000  177.000000
mean   322.967994  330.452042  ...          0.069350    0.024638
std    225.983130  229.402158  ...          0.113972    0.035376
min     19.870000   20.480000  ...         -0.146133   -0.109593
25%    149.730000  159.270000  ...         -0.027325    0.012157
50%    220.640000  230.420000  ...          0.079105    0.033393
75%    572.130000  583.000000  ...          0.166286    0.050725
max    773.440000  784.750000  ...          0.249996    0.061205

[8 rows x 27 columns]

In [186]:
non_anomaly = data[data['is_anomaly'] == 0]
non_anomaly.describe()

             close         high  ...  volatility_score    cum_score
count  3350.000000  3350.000000  ...       3350.000000  3350.000000
mean    228.161823   230.841078  ...          0.192151     0.156442
std     186.058896   188.195979  ...          0.065179     0.034836
min      17.729000    18.270000  ...         -0.112156     0.061800
25%      96.532500    97.632500  ...          0.181418     0.133260
50%     174.240000   176.175000  ...          0.214793     0.164490
75%     298.887500   302.542500  ...          0.233780     0.183692
max     790.000000   796.250000  ...          0.253422     0.216120

[8 rows x 27 columns]

## For all the 20 datas we have !

In [187]:
### Creating datasets for the top 20 companies 
watchlist = {
    "AAPL":  "Apple",
    "MSFT":  "Microsoft", 
    "NVDA":  "Nvidia",
    "GOOGL": "Alphabet (Google)",
    "AMD":  "AMD",
    "META":  "Meta (Facebook)",
    "TSLA":  "Tesla",
    "NFLX": "Netflix",
    "LLY":   "Eli Lilly",
    "AVGO":   "Broadcom",
    "MU":    "Micron Technology",
    "QCOM":   "Qualcomm",
    "UNH":   "UnitedHealth",
    "WMT":   "Walmart",
    "MA":    "Mastercard",
    "JNJ":   "Johnson & Johnson",
    "PG":    "Procter & Gamble",
    "HD":    "Home Depot",
    "ORCL":  "Oracle",
    "JPM": "JPMorgan Chase"
}

In [188]:
for key,value in watchlist.items():
    data_partition(key)
features = [['price_return','Price_Swing'], ['volatility_diff', 'Volatility_30Days'], ['volume_z_diff', 'volume_zscore30Days']]
for key,value in watchlist.items():
    iso_runner(key)
    print(f"{key} done")

KeyError: "['MASignal'] not in index"

In [ ]:
data = pd.read_parquet('../updatedtop20datasets/AVGO.parquet')
data.head(5)

                       date    close  ...  volatility_score  cum_score
0 2012-05-18 00:00:00+00:00  38.2318  ...          0.133157   0.070190
1 2012-05-21 00:00:00+00:00  34.0300  ...          0.133157   0.055015
2 2012-05-22 00:00:00+00:00  31.0000  ...          0.133157   0.064989
3 2012-05-23 00:00:00+00:00  32.0000  ...          0.133157   0.139023
4 2012-05-24 00:00:00+00:00  33.0300  ...          0.133157   0.131261

[5 rows x 29 columns]